const express = require('express')
const app = express()

app.use('/', express.static('demo'))
app.use('/css', express.static('css'))
app.use('/dist', express.static('dist'))
app.use('/src', express.static('src'))
app.use('/external', express.static('external'))
app.use('/node_modules', express.static('node_modules'))
app.listen(80, () => console.log('Example app listening on port 80!'))
